spring.application.name=task-tracker-scheduler

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.group-id=scheduler

spring.kafka.producer.properties[spring.json.add.type.headers]=false
